### ISSUE TITLE
Consider allowing setting up custom headers on the HTTPS module

### ISSUE THREAD

**Issue by guxlightyear** [ribbybibby/ssl_exporter#112]
When using SSLExporter it is difficult to differentiate legitimate customer requests from requests issued by the SSLExporter to validate the certificate of the server.

A way of doing so would be to allow customising the HTTPS module with extra headers, such as:
```
modules:
  https:
    prober: https
    headers:
       my-custom-header: my-custom-value
```

This would enable backend servers, monitoring agents, etc, to identify these requests.
