### ISSUE TITLE
Using  ssl_exporter with k8s

### ISSUE THREAD

**Issue by JohanJermey** [ribbybibby/ssl_exporter#12]
Hi,

Thanks for creating this project! @ribbybibby 
I want to use the ssl_exporter on K8S and I've the following questions:

1. I use Prometheus , did I need to install something in addition in the cluster to use the ssl_exporter? I saw that you have provided a docker image but what is the best way to use it on K8S, should I create k8s service ? 

2. How should I define the current target ,I want to check the target of the current  cluster which Prometheus is deployed in, what I should put inside the target config ? 

Thanks!

**Comment by ribbybibby** [comment]
Hi @JohanJermey, thanks for the issue.

1. I haven't ran ssl_exporter in Kubernetes myself so I can't give you a tried and tested method or a quick example but, yes, I think you should probably define a Service and a Deployment.

2. It depends what you mean by the 'target of the current cluster'. Do you mean the api server certificate?

**Comment by ribbybibby** [comment]
Here's a Service and Deployment that work for me in minikube:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ssl-exporter
  name: ssl-exporter
spec:
  ports:
    - name: ssl-exporter
      protocol: TCP
      port: 9219
      targetPort: 9219
  selector:
    app: ssl-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssl-exporter
  template:
    metadata:
      name: ssl-exporter
      labels:
        app: ssl-exporter
    spec:
      initContainers:
        # Install kube ca cert as a root CA
        - name: ca
          image: alpine
          command:
            - sh
            - -c
            - |
              set -e
              apk add --update ca-certificates
              cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/kube-ca.crt
              update-ca-certificates
              cp /etc/ssl/certs/* /ssl-certs
          volumeMounts:
            - name: ssl-certs
              mountPath: /ssl-certs
      containers:
        - name: ssl-exporter
          image: ribbybibby/ssl-exporter:v0.6.0
          ports:
            - name: tcp
              containerPort: 9219
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
      volumes:
        - name: ssl-certs
          emptyDir: {}
```
Note the `initContainer` that adds the api server ca cert to the root certs. This allows you to probe the apiserver in addition to any other target backed by the standard set of root certs. If you're only interested in targeting the api server you could remove this, the `volume` and the `volumeMounts` and instead use the arg `--tls.cacert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`.

Assuming you deploy ssl-exporter in the same namespace as Prometheus, this `scrape_config` should suffice:
```
scrape_configs:
  - job_name: ssl-exporter
    metrics_path: /probe
    static_configs:
      - targets:
        - kubernetes.default.svc:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ssl-exporter:9219
```

**Comment by JohanJermey** [comment]
Hi @ribbybibby 

Thank you very much this is awesome! , you was quick and this is really neat! 

 I deployed successfully your example, few questions calcification.

![image](https://user-images.githubusercontent.com/50859891/70510632-fa9d8580-1b37-11ea-93b8-618ff96954f6.png)


1. I see the ssl exporter in the target when I click on the link: `http://ssl-exporter:9219/probe?target=kubernetes.default.svc:443` , and nothing showing, any idea? 

2. we are using `istio` and our certificate which we need to monitor is defiend like

```
tls:
   mode: SIMPLE
   privateKey: /etc/istio/oss-tls/tls.key
   serverCertificate: /etc/istio/oss-tls/tls.crt

``` 

How can I configure it  to look into it ? 


Thanks a lot!

**Comment by ribbybibby** [comment]
1. Do you mean that when you click on the link in the target list you're getting a timeout or some other error? Unless you can resolve `ssl-exporter` and route to the service IP in the cluister from your local machine or wherever you're viewing this page, then I wouldn't expect it to work tbh. The fact that the state is UP tells me its reachable from the prometheus server, which is all that really matters.
2. I've never used istio, so you're going to have to give me more information. But essentially you need to find the address or addresses that will use that certificate and define them as a target in your prometheus scrape config.

**Comment by JohanJermey** [comment]
1. Yes, I try to run it and nothing is shown, do you have some hint how could I make it work with dummy certificate , I want to verify that this is working ...
I think your soultion is a lot better , but maybe something like this https://www.robustperception.io/get-alerted-before-your-ssl-certificates-expire but for K8S cluster when you put some dummy certificate and use ssl_exporter to validate it.

2. Yes we are start using istio lately , basically we are mounting the tls to each pod the needs it, I However as this is new topic on our landscape I'll invistage all the aspects and let you know soon

Thanks you very much @ribbybibby

**Comment by ribbybibby** [comment]
You can test it by querying for one of the metrics, like `ssl_cert_not_before`. If you see series in Prometheus, then it's working. 

Then, you can achieve what that blog post achieves with an alert rule like:
```
groups: 
  - name: ssl_expiry.rules 
    rules: 
      - alert: SSLCertExpiringSoon 
        expr: ssl_cert_not_after - time() < 86400 * 30
        for: 10m
```
