### ISSUE TITLE
Unable to use list of specific files in file module - cannot unmarshal !!seq into string

### ISSUE THREAD

**Issue by ilyadiff** [ribbybibby/ssl_exporter#202]
When I specify a list of certificate files in this desired configuration
```
---
default_module: file
modules:
  file:
    prober: file
    target:
      - "/etc/opensearch/os01_http.pem"
      - "/etc/opensearch/os01_transport.pem"
```
I get an error

`caller=ssl_exporter.go:143 level=error  msg="error parsing config file: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!seq into string
`
And so I have to use the following configuration to specify the necessary files.
```
---
default_module: file
modules:
  file1:
    prober: file
    target: "/etc/opensearch/os01_http.pem"
  file2:
    prober: file
    target: "/etc/opensearch/os01_transport.pem"
```

and it works for me, but it's inconvenient for a number of reasons. 
I can't specify all files by mask like `/etc/opensearch/*_*.pem` inside the directory
because, for example, there may be other certificates in the catalog that do not need to be monitored and there is no way to exclude them from monitoring

Is it possible to correct this behavior and make the "target" parameter to be a list ?

**Comment by laaber** [comment]
Hi,

I've been struggeling with the configuration, too. You can skip the "target" parameter in the config file and pass the target manually. Well, prometheus can pass it for us :)

ssl_exporter.yml:
```
default_module:
modules:
  myfile:
    prober: file
```

And in prometheus.yml under "scrape_configs" add a new job:
```
  # Scrape a list of files
  - job_name: 'ssl_exporter_file'
    scrape_interval: 60s
    metrics_path: /probe
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.d/ssl_exporter_file.yml
    params:
      module: ['myfile']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: ssl_target
      - target_label: __address__
        replacement: localhost:9219 # SSL exporter.
```
Finally, the target list, /etc/prometheus/targets.d/ssl_exporter_file.yml:

```
- targets:
    - /usr/share/ca-certificates/mozilla/SecureSign_RootCA11.crt
    - /usr/share/ca-certificates/mozilla/QuoVadis_Root_CA_2_G3.crt
```

Now you can add files to the list and prometheus will add them automatically, without manually reloading the config of anything.
Be aware this method allows to use a web browser to specify the files manually, too, so someone can look up random certificates the ssl_exporter's process can access.
