### ISSUE TITLE
configure module to use self signed cert

### ISSUE THREAD

**Issue by Skull0ne** [ribbybibby/ssl_exporter#206]
Hi

as issue https://github.com/ribbybibby/ssl_exporter/issues/73 is closed I'm opening a new one as I'm facing the same issue.

I followed what was said in the ticket but I still get the error "x509: certificate signed by unknown authority"

Here is my config : 
deployment : 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osd-ssl-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    spec:
      containers:
      - args:
        - --config.file=/etc/ssl-exporter/modules.conf
        name: ssl-exporter
        ports:
        - containerPort: 9219
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/ssl-exporter
          name: config-volume
        - mountPath: /etc/ssl/certs/ca
          name: ca-cert
      volumes:
      - configMap:
          defaultMode: 420
          name: ssl-exporter-configmap
        name: config-volume
      - name: eidos-ca
        secret:
          defaultMode: 420
          secretName: ca-cert
```

configmap : 
```
apiVersion: v1
data:
  modules.conf: |
    modules:
      https:
        prober: https
      https_self_signed:
        prober: https
        tls_config:
          ca_file: /etc/ssl/certs/ca-cert.crt
kind: ConfigMap
metadata:
  name: ssl-exporter-configmap
  namespace: monitoring
```

Result : 
```
curl  'osd-ssl-exporter.monitoring:9219/probe?target=https://myurl.com&module=https_self_signed'
# HELP ssl_probe_success If the probe was a success
# TYPE ssl_probe_success gauge
ssl_probe_success 0
# HELP ssl_prober The prober used by the exporter to connect to the target
# TYPE ssl_prober gauge
ssl_prober{prober="https"} 1
```

Thanks
