### ISSUE TITLE
Not able configure FTP endpoint 

### ISSUE THREAD

**Issue by guptaalok20** [ribbybibby/ssl_exporter#39]
I'm trying to setup monitoring for SSL certificates over FTP and did below configurations:

1. Setting config:
modules:
  tcp_ftp_starttls:
    prober: tcp
    tcp:
      starttls: ftp

2. Setting scrape config in prometheus:
job_name: "xyz"
    scrape_interval: 60s
    metrics_path: /probe
    static_configs:
      - targets:
        - <IP_Address>:22
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9319

But this does not seem to be working. Am i missing something?

**Comment by ribbybibby** [comment]
When you say that it isn't working, what do you mean? Do you get any messages in the logs? What metrics do you get back?

Looking at your scrape config, I think the issue is probably that you aren't setting the module you've defined as a parameter in your scrape config:
```yaml
  - job_name: 'xyz'
    scrape_interval: 60s
    metrics_path: /probe
    params:
      module: ["tcp_ftp_starttls"] # <----- module
    static_configs:
      - targets:
        - <IP_Address>:22
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9319
```
