### ISSUE TITLE
context problem

### ISSUE THREAD

**Issue by offlinejke** [ribbybibby/ssl_exporter#41]
I've tried to configure ssl-exporter, but prometheus gives me context deadline error.
Look please at my config, and tell what i missed.
ss-exporter:
```
modules:
  https:
    prober: https
  https_insecure:
    prober: https
    tls_config:
      insecure_skip_verify: true
```
prometheus:
```
  - job_name: 'ssl'
    metrics_path: /probe
    params:
      module: ["https"]
    static_configs:
      - targets:
        - "www.google.com:443"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 88.198.189.243:9219
```
