### ISSUE TITLE
how to probe https non 443 port e.g (https://example.com:1122)

### ISSUE THREAD

**Issue by tahir59** [ribbybibby/ssl_exporter#58]

**Comment by ribbybibby** [comment]
Hi @tahir59. This should work:
```
scrape_configs:
  - job_name: 'ssl'
    metrics_path: /probe
    params:
      module: ["https"]
    static_configs:
      - targets:
        - 'https://example.com:1122'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9219  # SSL exporter.
```

Assuming that `'https://example.com:1122'` is changed to a valid host and port combination and `127.0.0.1:9219` is the address of your ssl exporter instance.

**Comment by tahir59** [comment]
Hi @ribbybibby, refer the log below

cert-exporter-2_1  | time="2020-11-13T08:14:15Z" level=error msg="error=Get \"https://consul.test.local:8501\": x509: certificate signed by unknown authority target=https://consul.test.local:8501 prober=https timeout=10s" source="ssl_exporter.go:91"

  - job_name: "ssl"
    metrics_path: /probe
    params:
      module: ["https"]
    static_configs:
      - targets:
          - consul.test.local:8501
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: cert-exporter-2:9219

**Comment by ribbybibby** [comment]
```
"error=Get "https://consul.test.local:8501\": x509: certificate signed by unknown authority
```

This probably means the ssl_exporter doesn't have access to the CA cert that issued the certificate for `consul.test.local`. You either need to install it into the system certs where ssl_exporter is running, or pass it explicitly with `tls_config.ca_file` in a custom module configuration.

```
modules:
  https_consul:
    prober: https
    tls_config:
      ca_file: /etc/tls/ca.crt
```

https://github.com/ribbybibby/ssl_exporter#configuration-file
https://github.com/ribbybibby/ssl_exporter/blob/master/examples/ssl_exporter.yaml
