### ISSUE TITLE
How to add self signed certificates 

### ISSUE THREAD

**Issue by guptaalok20** [ribbybibby/ssl_exporter#59]
We have a few certificates which are self signed and I see below errors while trying to monitor them:
x509: certificate signed by unknown authority

Is there a way I can add self-signed certificates to avoid these errors? 

Thank you very much for your help and appreciate your support.

**Comment by ribbybibby** [comment]
There are a few options. If you have the CA certificate you issued the certificates with, you could install it into the system certs where ssl_exporter is running, or pass it explicitly with `tls_config.ca_file` in a custom module configuration.

```
modules:
  tcp_self_signed:
    prober: tcp
    tls_config:
      ca_file: /etc/tls/ca.crt
```

Otherwise, you could disable verification with `tls_config.insecure_skip_verify`:
```
modules:
  tcp_insecure:
    prober: tcp
    tls_config:
      insecure_skip_verify: true
```
https://github.com/ribbybibby/ssl_exporter#configuration-file
https://github.com/ribbybibby/ssl_exporter/blob/master/examples/ssl_exporter.yaml
