### ISSUE TITLE
RE: No cert metrics when target has expired or invalid certificate #37

### ISSUE THREAD

**Issue by wHiteeeeeeeee** [ribbybibby/ssl_exporter#60]
Hi, I tried to add:
```
modules:
tcp_insecure:
prober: tcp
tls_config:
insecure_skip_verify: true
```
to my ssl_exporter.yml, but i doesn't work. My ssl_exporter.yml file:
```
modules:
https_insecure:
prober: https
tls_config:
insecure_skip_verify: true
tcp:
prober: tcp
tcp_insecure:
prober: tcp
tls_config:
insecure_skip_verify: true
```
I need to add something more to yml to work perfectly? ssl_cert_not_after is working fine like other's metrics, but I don't
have certs that expired in ssl_cert_not_after.

Thanks for your help!

**Comment by ribbybibby** [comment]
What does your scrape config in Prometheus look like? Are you setting the module parameter to `tcp_insecure`?

**Comment by wHiteeeeeeeee** [comment]
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.16.155.151:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'blackbox'
    metrics_path: /probe
    scheme: http
    params:
      module: [http_2xx]
    file_sd_configs:
          - files:
                - /etc/blackbox/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.16.155.151:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'ssl'
    metrics_path: /probe
    scheme: http
    static_configs:
     - targets:
        - 'youtube.com:443'
        - 'prometheus.io:443'
        - 'cuk.pl:443'
        - 'launcher.uat.agent.nau.pl:443'
        - 'expired.badssl.com:443'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.16.155.151:9219  # SSL exporter.
    tls_config:
      insecure_skip_verify: true
```
Do i need to add module tcp? Sorry I'm begginer in prometheus ;-)

**Comment by ribbybibby** [comment]
You should set the module in the params of the ssl scrape job:
```
  - job_name: 'ssl'
    metrics_path: /probe
    scheme: http
    params:
      module: ["tcp_insecure"] # <----- set the module in the params
    static_configs:
     - targets:
        - 'youtube.com:443'
        - 'prometheus.io:443'
        - 'cuk.pl:443'
        - 'launcher.uat.agent.nau.pl:443'
        - 'expired.badssl.com:443'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.16.155.151:9219  # SSL exporter.
```

**Comment by wHiteeeeeeeee** [comment]
Now i got something like this:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.16.155.151:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'blackbox'
    metrics_path: /probe
    scheme: http
    params:
      module: [http_2xx]
    file_sd_configs:
          - files:
                - /etc/blackbox/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.16.155.151:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'ssl'
    metrics_path: /probe
    scheme: http
    params:
      module: ["tcp_insecure"]
    static_configs:
     - targets:
        - 'youtube.com'
        - 'prometheus.io:443'
        - 'cuk.pl:443'
        - 'launcher.uat.agent.nau.pl:443'
        - 'http://expired.badssl.com'
        - 'http://wrong.host.badssl.com'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.16.155.151:9219  # SSL exporter.
```
and ssl_exporter.yml:
```
modules:
  https:
    prober: https
  http:
    prober: http
    tls_config:
      insecure_skip_verify: true
  tcp_insecure:
    prober: tcp
    tls_config:
      insecure_skip_verify: true
```
and i doesn't work neither. What is wrong?
